### ISSUE TITLE
Add support for AMPE token to batching server

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/oracle-pallet#10]
We want to have the latest price of the AMPE token on-chain. So far, we are feeding the AMPE price manually once per week and we set it to a fixed price of 1$. However, we should add support for the AMPE token to the batching server so that the latest price of the AMPE token is updated on every block and we don't need to feed it manually anymore.

## TODO
We need to change the logic of the batching server to:
- work for a new asset with `blockchain` = `Amplitude` and `symbol` = `AMPE`. Capitalization should _not_ matter here. 
- fetch the price for this asset from our Amplitude squid (https://squid.subsquid.io/amplitude-squid/graphql) with the following query. The value of `ethPrice` represents the price of AMPE in USD.
```
query MyQuery {
  bundleById(id: "1") {
    id
    ethPrice
  }
}
```
- be configured to use the AMPE price. Might be best to add `AMPLITUDE:AMPE` to the list of default values [here](https://github.com/pendulum-chain/oracle-pallet/blob/b8c5bd0f0e756d83868f1dd982d45792a662bfd7/dia-batching-server/src/args.rs#L31).

## GraphQL
For the graphql queries, we should use some crate like [graphql-client](https://github.com/graphql-rust/graphql-client). The schema can be found [here](https://github.com/pendulum-chain/pendulum-squids/blob/main/schema.graphql).

## To be done
- add the AMPE token to the list of supported currencies of the DIA pallet on-chain

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/oracle-pallet/10?planning-poker) with Zenhub @adelarja @b-yap @ebma @TorstenStueber

**Comment by TorstenStueber** [comment]
@ebma what is the batching server?

What is the flow of data here: the batching server should request the price from the squid, which gets the price from the chain and then feed it into the chain? Isn't that circular?

**Comment by ebma** [comment]
The batching server is the service that provides prices from the DIA price feed to the off-chain worker. So on every block the offchain worker tries to get the latest prices of the designated assets from the batching server. 

The difficulty here is how we derive the AMPE price. AMPE is not listed on a CEX so DIA has no data for it. What we decided to do instead is to base the AMPE price on the ratio of the liquidity in the AMPE/KSM pool. So we check how many AMPE are 'equal' to 1 KSM according to the current pool ratio and then use the latest dollar price of KSM to define the AMPE price.

The ticket describes that the batching server should query the price from the indexer because the indexer does this price derivation on each block. However, we can also change the batching server to connect to Amplitude and query the on-chain ratio of the AMPE/KSM pool and then do the price derivation locally. IMO querying it from the indexer is easier and faster.

**Comment by TorstenStueber** [comment]
Makes perfect sense now and I also do remember what the batching server is now. Thanks for the explanation.

**Comment by ebma** [comment]
@pendulum-chain/product I realized that implementing this ticket has an implication for Spacewalk issue requests on Amplitude. At the moment we manually feed a price for AMPE of $0.1 to Amplitude. Once we support the 'actual price' represented by the Zenlink pool, the value of the AMPE token will be around $0.0042. Thus, users will have to lock twice as many AMPE as griefing collateral for issue requests than they have to lock right now. Just FYI. This is not a flaw but important for the overall bridge security.

**Comment by vadaynujra** [comment]
Makes sense @ebma and how it is expected to work.

**Comment by prayagd** [comment]
@b-yap does this require any runtime upgrade or root transaction?

**Comment by ebma** [comment]
No it does not.
