### ISSUE TITLE
Configure CORS for the batching server 

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/oracle-pallet#27]
## Context

The batching server currently does not configure CORS and by default, all requests from a browser are disabled. We want to enable CORS in order to be able to query prices from the portal frontend.

This is needed for https://github.com/pendulum-chain/portal/issues/439. 

## TODO

- Add [actix_cors](https://docs.rs/actix-cors/latest/actix_cors/) middleware to the batching server.
- Configure it so that it can be used to query data from the  `/currencies` POST endpoint.
- It should at least allow the origin `portal.pendulumchain.org`. We can also think about enabling netlify deployments in the CORS settings.

**Comment by ebma** [comment]
@pendulum-chain/product this is blocking https://github.com/pendulum-chain/portal/issues/439 and in order to unblock it we should work on this very soon.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/oracle-pallet/27?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
