### ISSUE TITLE
Enable price feeds for PEN and ARS on batching server

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/oracle-pallet#30]
## Context 

Since in the future, the PEN (Peruvian Peso) and ARS (Argentinian Sol) asset prices are needed on-chain, we need to add them to the configuration of the batching server. 

## TODO 

- [ ] Add them to the default list of supported currencies [here](https://github.com/pendulum-chain/oracle-pallet/blob/2c4f9b31274680390eb848bbe0fc28be845e5d61/dia-batching-server/src/args.rs#L28) 
- [ ] Redeploy the batching server. The batching server is configured to always use the default parameter of the supported currencies, so this should be enough to apply the setting. The redeployment should be automatically triggered when merging a PR to `main`.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/oracle-pallet/30?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
Could `FIAT:PEN-USD` ever lead to confusion with PEN (Pendulum)? The `FIAT:` prefix describes/implies that the asset between the `:` and `-` is a fiat currency and therefore can never be PEN (Pendulum), correct?

**Comment by ebma** [comment]
Yes exactly. Since we distinguish between forex and crypto prices with the `blockchain` field we can disambiguate the two.
